server:
  port: 8084

spring:
  application:
    name: dispatch-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/dispatch_db}
    username: ${SPRING_DATASOURCE_USERNAME:dispatch_user}
    password: ${SPRING_DATASOURCE_PASSWORD:dispatch_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
